### PR TITLE
taho

### PR DESCRIPTION
**Pull request by tahsnerken47**
spas heval

### CODE REVIEW

**Comment by erkanozclk** [comment]
it getting conflict now in the repo, i cant accept your pull request. but this is the way you going to create a pull request. Congratulations for first  PR

**Comment by tahsnerken47** [comment]
Did I make a mistake while pulling request

**Comment by erkanozclk** [comment]
Noop, we are all create hello in same file, it get conflict. you did right process. You should do next time. :)

**Comment by tahsnerken47** [comment]
I typed spas Erkan on the erkan class .

**Comment by tahsnerken47** [comment]
Is it bc we all typed in same class or same context

**Comment by erkanozclk** [comment]
Yes and no. 
we were typed same line. if do in same class it is okay if you dont do in same line.

**Comment by tahsnerken47** [comment]
Ok I got it spas bra

**Pull request closed without merging**
